#!/bin/bash

function mac_matching() {
    MAC_ADDRESS="$(cat /sys/class/net/wlan0/address)"
sudo bash -c 'cat > /etc/udev/rules.d/70-persistent-net.rules' << EOF
SUBSYSTEM=="ieee80211", ACTION=="add|change", ATTR{macaddress}=="${MAC_ADDRESS}", KERNEL=="phy0", \
  RUN+="/sbin/iw phy phy0 interface add ap0 type __ap", \
  RUN+="/bin/ip link set ap0 address ${MAC_ADDRESS}
EOF
echo "Populate /etc/udev/rules.d/70-persistent-net.rules"
}

function rebuild_hook() {
    if [ -f "/boot/ideasky_rebuild" ]; then
        # 檔案 /boot/ideasky_rebuild 存在
        echo "File /boot/ideasky_rebuild exists."
        mac_matching
        sudo rm /boot/ideasky_rebuild
        sudo bash -c "reboot"
    else
        # 檔案 /boot/ideasky_rebuild 不存在
        echo "File /boot/ideasky_rebuild does not exists."
    fi
}

function mac_check() {
    MAC_ADDRESS="$(cat /sys/class/net/wlan0/address)"
    OLD_ADDRESS="$(sed -r 's/^([^"]*"){5}([^"]*).*/\2/' /etc/udev/rules.d/70-persistent-net.rules)"
    echo $MAC_ADDRESS
    echo $OLD_ADDRESS
    if [ "$MAC_ADDRESS" != "$OLD_ADDRESS" ]; then
        echo "Start Rebuilding Interface"
        mac_matching
        sudo bash -c "reboot"
    else
        echo "There is no need for Rebuilding"
    fi
}

while :
do 
    mac_check
    rebuild_hook    
    sleep 5
done

# sed 's/\(macaddress\}=="\)[^"]*/\1/' ./mac
# sed -i 's/\(macaddress\}=="\)[^"]*/\1'$MAC_ADDRESS'/' ./mac
# sed -i 's/\(ap0 address \).*/\1'$MAC_ADDRESS'/' ./mac
# cat ./mac
# sed 's/^"\(.*\)".*/\1/' a
# grep -oP 'macaddress}==".*?"' ./mac
# grep -oP 'ap0 address .*' ./mac
# grep -oP '"([^"]*)"' ./mac