#!/bin/bash

# Error management
set -o errexit
set -o pipefail
set -o nounset

usage() {
    cat 1>&2 <<EOF
Configures simultaneous AP and Managed Mode Wifi on Raspberry Pi
USAGE:
    rpi-wifi -a <ap_ssid> [<ap_password>] -c <client_password> [<client_password>]

    rpi-wifi -a MyAP myappass -c MyWifiSSID mywifipass
PARAMETERS:
    -a, --ap            AP SSID & password
    -c, --client        Client SSID & password
    -i, --ip            AP IP
FLAGS:
    -n, --no-internet   Disable IP forwarding
    -h, --help          Show this help
EOF
    exit 0
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -c|--client)
    CLIENT_SSID="$2"
    CLIENT_PASSPHRASE="$3"
    shift
    shift
    shift
    ;;
esac
done

sudo bash -c 'cat > /etc/wpa_supplicant/wpa_supplicant.conf' << EOF
country=TW
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
        ssid="${CLIENT_SSID}"
        $([ $CLIENT_PASSPHRASE ] && echo "psk=\"${CLIENT_PASSPHRASE}\"")
        id_str="AP1"
}
EOF

wpa_cli -i wlan0 reconfigure
sudo ifdown --force wlan0
sudo ifup wlan0
sudo dhclient wlan0